### ISSUE TITLE
Questions on how to install

### ISSUE THREAD

**Issue by JustOneMoreDog** [seffparker/icinga2-teams-notification#1]
Hello There,

I came across your script and would like to know how I would add this to our Icinga2 deployment please.

Thanks!

**Comment by seffparker** [comment]
Simply copy the two `teams-notification-` confs to `/etc/icinga2/conf.d/` directory and configure your existing host or service configuration like the provided `sample.conf`

**Comment by seffparker** [comment]
I have added installation instructions [here](https://github.com/seffparker/icinga2-teams-notification/blob/main/README.md#installation-and-basic-configuration)
