### ISSUE TITLE
Use teams_notifications_channel var

### ISSUE THREAD

**Issue by gianmarco-mameli** [seffparker/icinga2-teams-notification#2]
Hi, I've configured your command on our Icinga2 infrastructure, I would ask you how to use the var "teams_notifications_channel", because we want to separate notification to various channels, but I think the only method is different webhook urls.
There's any method to use the var? thanks in advance

**Comment by seffparker** [comment]
Unlike Slack, the Teams webhooks are hard-bound to a channel and cannot be changed via the HTTP POST data, like we usually do for Slack. See this [discussion](https://stackoverflow.com/questions/65339115/ms-teams-webhook-specify-channel)

The variable *teams_notifications_channel* is dummy here after the plugin ported from [icinga2-rich-slack-notification](https://github.com/seffparker/icinga2-rich-slack-notification)

**Comment by gianmarco-mameli** [comment]
Ok, thanks, we try to solve the problem adding some var on hosts to change the webhook url
