### ISSUE TITLE
teams-notifications-notification-**services' of type 'Notification': Validation failed: No users/user_groups specified.**

### ISSUE THREAD

**Issue by gauravsuryawanshi0806** [seffparker/icinga2-teams-notification#3]
Hi, I've configured your command on our Icinga2 infrastructure,
After adding configuration i am getting below error while doing validation.
can you please help the same.

Error : 

[2021-07-20 10:55:10 +0200] critical/config: Error: Validation failed for object '10.1.1.1!ping4!teams-notifications-notification-**services' of type 'Notification': Validation failed: No users/user_groups specified.**
Location: in /etc/icinga2/conf.d/teams-notifications-configuration.conf: 47:1-47:73
/etc/icinga2/conf.d/teams-notifications-configuration.conf(45): }
/etc/icinga2/conf.d/teams-notifications-configuration.conf(46):
/etc/icinga2/conf.d/teams-notifications-configuration.conf(47): apply Notification "teams-notifications-notification-services" to Service {
                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/etc/icinga2/conf.d/teams-notifications-configuration.conf(48):   import "teams-notifications-user-configuration-services"
/etc/icinga2/conf.d/teams-notifications-configuration.conf(49):

[2021-07-20 10:55:10 +0200] critical/config: Error: Validation failed for object '10.1.1.1!Memory!teams-notifications-notification-services' of type 'Notification': Validation failed: No users/user_groups specified.
Location: in /etc/icinga2/conf.d/teams-notifications-configuration.conf: 47:1-47:73
/etc/icinga2/conf.d/teams-notifications-configuration.conf(45): }
/etc/icinga2/conf.d/teams-notifications-configuration.conf(46):
/etc/icinga2/conf.d/teams-notifications-configuration.conf(47): apply Notification "teams-notifications-notification-services" to Service {
                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/etc/icinga2/conf.d/teams-notifications-configuration.conf(48):   import "teams-notifications-user-configuration-services"
/etc/icinga2/conf.d/teams-notifications-configuration.conf(49):

**Comment by gauravsuryawanshi0806** [comment]
@seffparker  : Can you please have a look into the same.

**Comment by seffparker** [comment]
In your Host Object for 10.1.1.1, make sure the `vars.notify_users` array is defined with the required users as notification receivers. You may also declare it inside a host Template and import in to the host Object 10.1.1.1. See /sample.conf for examples.

P.S.: There is a fallback user `icingaadmin` for this purpose, but it seems the code didn't catch it. I'll push a fix for this later.

**Comment by seffparker** [comment]
I have fixed the fallback user when the notify_users variable is not defined in the host Object.

See commit fb1a4f7
