### ISSUE TITLE
Add possibility to have different notifications in a single service

### ISSUE THREAD

**Issue by Alucard616** [seffparker/icinga2-teams-notification#4]
Hi there!

We like to have a possibility, to add a notification for only one service for one host.
Something like that:

`
object Host "myhost1.com" {
  address="myhost1.com"
  vars.os="Linux"

  vars.memory[""] = {
  }

  vars.users[""] = {
    notify_users = [ "myuser2" ]
    notification.teams = true
  }

  vars.load[""] = {
    load_wload1 = 1.6
    load_wload5 = 1.6
    load_wload15 = 1.6

    load_cload1 = 2
    load_cload5 = 2
    load_cload15 = 2
  }
  
  vars.notify_users = [ "myuser1" ]
  vars.notification.teams = true
`

**Comment by seffparker** [comment]
Can you please elaborate your requirement? The title and context are confusing each other.

1. Do you need to add multiple type of notifications (Teams, Slack, etc) for a single service?
1. Do you need to enable the Teams notification for a specific service in a specific host only?

**Comment by Alucard616** [comment]
sure thing :)
sorry for the confusion though.

It's the second.

In my example i want the notifications for load, memory and host (up|down) sent to the teams user "myuser1" but the notifications for the users check should be send to "myuser2".

I hope it's bit more clear now. :)

**Comment by seffparker** [comment]
I have implemented this feature in the branch https://github.com/seffparker/icinga2-teams-notification/tree/feature/service-notify-users

Now you can define `notify_users` in service, so only they will be notified about those services.

```
object User "myuser1" {
  import "generic-user"
  display_name = "My User 1"
  vars.teams_webhook_url = "https://outlook.office.com/webhook/aaaaaa/IncomingWebhook/bbbbbb"
}

object User "myuser2" {
  import "generic-user"
  display_name = "My User 2"
  vars.teams_webhook_url = "https://outlook.office.com/webhook/xxxxxx/IncomingWebhook/yyyyyy"
}

object Host "myhost1.com" {
  address = "myhost1.com"
  vars.os = "Linux"
  vars.notify_users = [ "myuser1" ]
  vars.notification.teams = true 
}

apply Service "load" {
  ...
}

apply Service "memory" {
  ...
}

apply Service "users" {
  ...
  vars.notify_users = [ "myuser2" ]
}
```

using the above configuration, `myuser1` receives Teams notifications about host(up|down), load, and memory. The user `myuser2` only receives about the service `users`.
