### ISSUE TITLE
Does this work with icinga director?

### ISSUE THREAD

**Issue by JohannAusRohan** [seffparker/icinga2-teams-notification#8]
Is it possible to get this running while using the director module?
I set up the `vars.notification.teams` as well as `vars.teams_webhook_url` and assigned them to the host and notification user. Notifications are not coming through and `icinga2 daemon -c` is reporting :

`[2023-07-26 11:41:05 +0200] warning/ApplyRule: Apply rule 'teams-notifications-notification-services' (in /etc/icinga2/conf.d/teams-notifications-configuration.conf: 48:1-48:73) for type 'Notification' does not match anywhere!
[2023-07-26 11:41:05 +0200] warning/ApplyRule: Apply rule 'teams-notifications-notification-hosts' (in /etc/icinga2/conf.d/teams-notifications-configuration.conf: 41:1-41:67) for type 'Notification' does not match anywhere!
`

**Comment by seffparker** [comment]
I didn't test it with Icinga Director, yet probably it would work.

Regarding the log messages, its a WARNING message since the conf didn't use the notification feature after it being defined. We have to enable the notification in the required services explicitly or via some imports like [sample conf](https://github.com/seffparker/icinga2-teams-notification/blob/main/sample.conf#L30-L32)

**Comment by JohannAusRohan** [comment]
After copying the scripts to the `/etc/icinga2/conf.d` location (is this the correct path for director?), I tried it like that:

1. created all vars in director "data fields" section, `vars.notification.teams` as boolean, `vars.teams_webhook_url` as string.
2. assigned `vars.teams_webhook_url` to user template and pasted the webhook URL to the corresponding field in the user setting
3. assigned `vars.notification.teams` to my host-template and set to YES
4. went to notification section in director, edited "assign where" to where `vars.notification.teams` is true
5. sent a custom notification 
6. no post is being created in teams, icinga2.logfile shows:

`[2023-07-26 11:36:06 +0200] information/Notification: Completed sending 'Custom' notification MYSERVERNAME!host notification always itsm' for checkable 'MYSERVERNAME' and user 'MYUSER' using command 'mail-host-notification'.`

**Comment by seffparker** [comment]
The notification object expects `true` or `false` for `vars.notification.teams`. If you have to use yes/no method, please modify the "Apply Notification" accordingly.

**Comment by JohannAusRohan** [comment]
sorry, I just edited my previous post because I noticed, I forgot to mention that. So I did that but unfortunately, it is still not posting in teams. I appreciate your help!

**Comment by seffparker** [comment]
I would suggest to manually modify the confs and make the plugin work. If yes, we can surely adapt it work via Director. Please keep conf backups before edits.

**Comment by slalomsk8er** [comment]
Yes, I use it with the director.

![image](https://github.com/seffparker/icinga2-teams-notification/assets/100971/40580482-8033-40ed-acfa-b908f2dfce87)
![image](https://github.com/seffparker/icinga2-teams-notification/assets/100971/f60c93e3-b1ab-4c36-85f9-9e299eb6c89d)
![image](https://github.com/seffparker/icinga2-teams-notification/assets/100971/f35b5906-a9f7-4cc6-8dfb-1489ef894742)
![image](https://github.com/seffparker/icinga2-teams-notification/assets/100971/fb3b2084-ad89-457f-8a62-f21be7a79dcc)
![image](https://github.com/seffparker/icinga2-teams-notification/assets/100971/36261661-e145-4092-90a4-6d65016c74b8)
![image](https://github.com/seffparker/icinga2-teams-notification/assets/100971/aac106d3-7c21-4be8-8723-ff62f132101b)

teams-notifications-configuration.conf
```
apply Notification "teams-notifications-notification-hosts" to Host {
  import "teams-notifications-user-configuration-hosts"
  interval = (host.vars.notification.interval) || 0

  assign where host.vars.enable_teams_notifications == true
}

apply Notification "teams-notifications-notification-services" to Service {
  import "teams-notifications-user-configuration-services"
  interval = (service.vars.notification.interval) || 0

  # enable globaly for all services on host but not if disabled for this host
  assign where host.vars.enable_teams_notifications == true && service.vars.enable_teams_notifications != false
}

apply Notification "teams-notifications-notification-services" to Service {
  import "teams-notifications-user-configuration-services"
  interval = (service.vars.notification.interval) || 0

  # only if not enabled globaly for host
  assign where service.vars.enable_teams_notifications == true && host.vars.enable_teams_notifications != true
}

template Notification "teams-notifications-user-configuration" {
    import "teams-notifications-default-configuration"
    users = (host.vars.notify_teams_bots) || (service.vars.notify_teams_bots) || vars.users_fallback
    vars.teams_notifications_webhook_url = "$user.vars.teams_webhook_url$"
    vars.teams_notifications_icinga2_base_url = "https://icinga.example.com/icingaweb2"
}
```
I hope I didn't miss a thing.

**Comment by JohannAusRohan** [comment]
Can you give directions on what confs you mean and how I should edit them in order to make it work? I am a bit clueless.Am 26.07.2023 12:45 schrieb Seff ***@***.***>:
I would suggest to manually modify the confs and make the plugin work. If yes, we can surely adapt it work via Director. Please keep conf backups before edits.

**Comment by JohannAusRohan** [comment]
thanks a lot! I cannot get it to work though. I rebuild everything in my environment according to your screenshots but still no success. To me, it is unclear how icinga even knows about `teams-notifications-configuration.conf` ? How does just copying it to conf.d make it known to the director? It seems I am missing something?

**Comment by seffparker** [comment]
By default, `*.conf` under `conf.d` directory are included by icinga2 server upon restart. Main conf has:
```
include_recursive "conf.d"
```
The initial warning messages ensure that the `teams-notifications-configuration.conf` already included. I believe Director only enable an easy way to manage the confs.

**Comment by JohannAusRohan** [comment]
I finally got it working. In `teams-notifications-configuration.conf` I had to edit lines 6 and 8 and rename them to fit my naming in the director. An obvious mistake I completely oversaw! Thanks for your time and help @seffparker  @slalomsk8er

**Comment by seffparker** [comment]
Glad to hear that it finally worked for you :tada: 

(closing this issue for now)

**Comment by UAnton** [comment]
> user [slalomsk8er]
And how to add command in a director? conf not command.
