### ISSUE TITLE
license unclear

### ISSUE THREAD

**Issue by moreamazingnick** [seffparker/icinga2-teams-notification#9]
Could you please specify a license for your work.
I think the original work is [Apache-2.0 license](https://github.com/nisabek/icinga2-slack-notifications/blob/master/LICENSE)
https://github.com/nisabek/icinga2-slack-notifications
Best Regards 
Nicolas

**Comment by seffparker** [comment]
I wasn't aware of that, thanks for pointing out. 

I have added the Apache 2.0 license

**Comment by moreamazingnick** [comment]
that was fast, thanks
